name: "Build, Push and Deploy a container image to Kubernetes"
description: "Build, Push and Deploy a container image to Kubernetes. Requires Microsoft.NET.Build.Containers package installed and a deployment folder to be present in the repository."

inputs:
  githubToken:
    description: "Access token provided by the calling action context, used to publish the packages and push the corresponding tag."
    required: true
  packageReadonlyPat:
    description: "Personal access token used to access the github private nuget source."
    required: true
  projectFolder:
    description: "Folder containing the project to build."
    required: true
    type: string
  imageName:
    description: "Name of the docker image to build."
    required: true
    type: string
  serviceName:
    required: true
    type: string
  environment:
    description: "Environment to deploy to."
    required: true
    type: string
  containerPublishType:
    description: "Type of container publish (api | worker)."
    required: true
    type: string
  imageTagPrefix:
    description: "Prefix of the docker image tag. If not provided, will be generated based on the environment."
    required: false
    type: string
    default: ""
  dotnetVersion:
    description: "Version of dotnet to use. Default is v7.x."
    required: false
    type: string
    default: "7.x"
  dockerRegistry:
    description: "Docker registry to push the image to."
    required: false
    type: string
    default: "docker.pkg.github.com"
  actionRef:
    description: "Run actions from this ref. Default is master."
    required: false
    default: "master"

runs:
  using: "composite"
  steps:
    - name: Checkout calling repo
      uses: actions/checkout@v3

    - name: Checkout actions repo
      uses: actions/checkout@v3
      with:
        repository: trakx/github-actions
        path: github-actions
        ref: ${{ inputs.actionRef }}

    - name: Set variable CONTAINER_IMAGE_TAG_PREFIX
      shell: bash
      run: |
        IMAGE_TAG="${{inputs.imageTagPrefix}}"
        if [[ -z "$IMAGE_TAG" ]]; then
          if [[ "${{inputs.environment}}" == "production" ]]; then
              IMAGE_TAG="prod"
          elif [[ "${{inputs.environment}}" == "stage" ]]; then
              IMAGE_TAG="stage"
          else
              IMAGE_TAG="dev"
          fi
        fi
        echo "CONTAINER_IMAGE_TAG_PREFIX=$IMAGE_TAG" >> $GITHUB_ENV

    - name: Build and push container image
      id: build-push-container
      uses: ./github-actions/build-push-container
      with:
        githubToken: ${{inputs.githubToken}}
        packageReadonlyPat: ${{inputs.packageReadonlyPat}}
        projectFolder: ${{ inputs.projectFolder }}
        imageName: ${{ inputs.imageName }}
        imageTagPrefix: ${{ env.CONTAINER_IMAGE_TAG_PREFIX }}
        containerPublishType: ${{ inputs.containerPublishType }}
        dotnetVersion: ${{ inputs.dotnetVersion }}
        dockerRegistry: ${{ inputs.dockerRegistry }}
        doCheckout: false

    - name: Deploy container image to Kubernetes
      id: deploy-container-k8s
      uses: ./github-actions/deploy-kubernetes
      with:
        environment: ${{inputs.environment}}
        imageTag: ${{steps.build-push-container.outputs.tag}}
        serviceName: ${{ inputs.serviceName }}
        imageName: ${{ inputs.imageName }}
        dockerRegistry: ${{ inputs.dockerRegistry }}
        doCheckout: false
