name: Code quality gate
description: "Runs a Qodana scan to asses code quality"

inputs:
  privateRepoTypes:
    description: "Types of private repos to add to the Qodana cache before running"
    required: true
    default: "['nuget']"
  packageReadonlyPat:
    description: "Personal access token used to access the github private nuget source."
    required: true
  dotnetVersion:
    description: "Version of dotnet to use. Default is v7.x."
    required: false
    default: "7.x"
  qodanaToken:
    description:  "Token used by Qodana to identify the project being analysed."
    required: true
  

runs:
  using: composite

  steps:
    - name: Restore and cache private nuget packages
      if: ${{ contains(fromJson(inputs.privateRepoTypes), 'nuget') }}
      uses: ./github-actions/restore-dotnet
      with:
        dotnetVersion: ${{inputs.dotnetVersion}}
        packageReadonlyPat: ${{packageReadonlyPat}}
        fetchDepth: 0

    - name: 'Qodana Scan'
      uses: JetBrains/qodana-action@v2023.2
      env:
          QODANA_TOKEN: ${{ inptus.qodanaToken }}
