name: Loads and outputs the event commit ids from artifact
description: Useful when there are workflows triggering other workflows, to allow the triggered workflows to know the event commit ids (when the event is a workflow_run).

inputs:
  workflowRunId:
    description: "The id of the workflow run to fetch the artifact from"
    required: false

outputs:
  eventCommits:
    description: "Commit ids loaded from artifact"
    value: ${{ steps.getEventCommits.outputs.eventCommits }}

runs:
  using: "composite"

  steps:
    # - name: Dump GitHub context
    #   env:
    #     GITHUB_CONTEXT: ${{ toJson(github) }}
    #   shell: bash
    #   run: echo "$GITHUB_CONTEXT"

    - name: "Load event commits from artifact (when event is workflow_run)"
      uses: actions/github-script@v6
      with:
          script: |
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{ inputs.workflowRunId || github.run_id }}
            });
            
            let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "ga-event-commits"
            })[0];
            
            let download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            
            let fs = require('fs');
            fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/ga-event-commits.zip`, Buffer.from(download.data));

    - name: Upload zipped artifact
      uses: actions/upload-artifact@v4
      with:
        name: zip-ga-event-commits
        path: ga-event-commits.zip
        retention-days: 1
        compression-level: 0
        overwrite: true

    - name: "Unzip ga-event-commits artifact"
      shell: bash
      run: unzip ga-event-commits.zip

    - name: "Load event commits from ga-event-commits unzipped file"
      uses: actions/github-script@v6
      id: readEventCommits
      with:
        script: |
          let fs = require('fs');
          let data = fs.readFileSync('./ga-event-commits.txt');
          // read the file content as text
          let eventCommits = data.toString();
          // logs the file content
          console.log('Unzipped file content: ', eventCommits);
          // set the output
          return eventCommits;

    - name: "Outputs ga-event-commits file content"
      id: getEventCommits
      shell: bash
      run: |
        echo "[DEBUG] Found event commits from artifact: ${{ steps.readEventCommits.outputs.result }}"
        echo "eventCommits=${{ steps.readEventCommits.outputs.result }}" >> $GITHUB_ENV
