name: Loads and outputs the event commit ids from artifact
description: Useful when there are workflows triggering other workflows, to allow the triggered workflows to know the event commit ids (when the event is a workflow_run).

inputs:
  workflowRunId:
    description: "The id of the workflow run to fetch the artifact from"
    required: false

outputs:
  eventCommits:
    description: "Commit ids loaded from artifact"
    value: ${{ steps.getEventCommits.outputs.eventCommits }}

runs:
  using: "composite"

  steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      shell: bash
      run: echo "$GITHUB_CONTEXT"

    - name: "Load event commits from artifact (when event is workflow_run)"
      uses: actions/download-artifact@v3
      with:
        name: ga-event-commits
        run-id: ${{ inputs.workflowRunId || github.run_id }}

    - name: Unzip event commits artifact
      shell: bash
      run: |
        unzip ga-event-commits.zip
        mv ga-event-commits.txt $GITHUB_OUTPUT

    - name: "Load event commits from ga-event-commits.txt"
      id: getEventCommits
      shell: bash
      run: |
        eventCommits=$(cat $GITHUB_EVENT_PATH/ga-event-commits.txt)
        echo "[DEBUG] Found event commits from artifact: $eventCommits"
        echo "eventCommits=$eventCommits" >> $GITHUB_OUTPUT
