name: Loads and outputs the event commit ids from artifact
description: Useful when there are workflows triggering other workflows, to allow the triggered workflows to know the event commit ids (when the event is a workflow_run).

inputs:
  workflowRunId:
    description: "The id of the workflow run to fetch the artifact from"
    required: false

outputs:
  artifactCommits:
    description: "Commit ids loaded from artifact"
    value: ${{ steps.getArtifactCommits.outputs.artifactCommits }}

runs:
  using: "composite"

  steps:
    - name: "Download ga-event-commits artifact"
      uses: actions/download-artifact@v4
      with:
        name: ga-event-commits
        run-id: ${{ inputs.workflowRunId || github.run_id }}
        github-token: ${{ github.token }}

    - name: "Load event commits from ga-event-commits unzipped file"
      id: getArtifactCommits
      shell: bash
      run: |
        artifactCommits=$(cat ga-event-commits.txt)
        echo "[DEBUG] Event commits fetched from ga-event-commits artifact: $artifactCommits"
        echo "artifactCommits=$artifactCommits" >> $GITHUB_ENV
