name: "Install GitHub CLI"

runs:
  using: "composite"
  steps:
    - name: Install GH CLI
      shell: bash
      run: |
        echo "[DEBUG] Installing GH CLI"
        curl -sL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
        sudo apt-get update
        sudo apt-get install gh

        echo "[DEBUG] GH CLI installed"
        gh --version
