name: "Pick Environment and RunnerName"
description: "Picks the right environment and runner based on the branch name"

outputs:
  environment:
    description: "Detected Environment"
    value: ${{ steps.detectStep.outputs.environment}}
  runnerName:
    description: "Detected RunnerName"
    value: ${{ steps.detectStep.outputs.runnerName}}

runs:
  using: "composite"
  steps:
    - name: "Detect Environment and Runner"
      shell: bash
      id: detectStep
      run: |
        
        if [[ "${{ github.ref }}" == "refs/heads/prod" || "${{ github.ref }}" == "refs/heads/master" ]]; then
            DETECTED_ENVIRONMENT="production"
            RUNNER_NAME="prod-trakx-runner"
        elif [[ "${{ github.ref }}" == "refs/heads/stage" ]]; then
            DETECTED_ENVIRONMENT="staging"
            RUNNER_NAME="stage-trakx-runner"
        else
            DETECTED_ENVIRONMENT="development"
            RUNNER_NAME="dev-trakx-runner"
        fi
        
        echo "Detected Environment is: $DETECTED_ENVIRONMENT"
        echo "Detected Runner is: $RUNNER_NAME"
        
        echo "environment=$DETECTED_ENVIRONMENT" >> $GITHUB_OUTPUT
        echo "runnerName=$RUNNER_NAME" >> $GITHUB_OUTPUT
