name: Evaluate Git Diff from a PR
description: "Evaluates the git diff from a PR and outputs the files that have been modified, added or deleted"

inputs:
  paths:
    description: "Paths to be verified, separated by comma"
    required: true
    default: "."

outputs:
  hasChanges:
    description: "Has changes"
    value: ${{ steps.evaluateStep.outputs.hasChanges }}

runs:
  using: "composite"
  steps:

    - name: "Detect Changes"
      id: files
      uses: jitterbit/get-changed-files@v1
      with:
        format: 'json'

    - name: "Evaluate Changes that are under the inputs.paths (split by comma)"
      id: evaluateStep
      shell: bash
      run: |
        IFS=',' read -ra paths <<< "${{ inputs.paths }}"
        hasChanges=false
        for path in "${paths[@]}"; do
          # ensure path does not start with ./
          path="${path#./}"

          # ensure path ends with /
          path="${path%/}/"

          echo "Checking if any file starts with $path"

          # check if any file starts with the path
          if [[ ${{ steps.files.outputs.all }} == *"$path"* ]]; then
            hasChanges=true
            break
          fi
        done
        # set the output with the result
        echo "hasChanges=$hasChanges" >> $GITHUB_OUTPUT
