name: Evaluate Git Diff from a PR
description: "Evaluates the git diff from a PR and outputs the files that have been modified, added or deleted"

inputs:
  # array of paths to be verified
  paths:
    description: "Paths to be verified, separated by comma"
    required: true
    default: "."

outputs:
  hasChanges:
    description: "Has changes"
    value: ${{ steps.evaluateStep.outputs.hasChanges }}

runs:
  using: "composite"
  steps:

    - name: "Detect Changes"
      id: files
      uses: jitterbit/get-changed-files@v1
      with:
        format: 'json'

    - name: Echo all files
      id: echoFiles
      shell: bash
      run: |
        echo "Files changed: ${{ steps.files.outputs.all }}"

    - name: "Evaluate Changes that are under the inputs.paths (split by comma) using bash"
      id: evaluateStep
      shell: bash
      run: |
        IFS=',' read -ra paths <<< "${{ inputs.paths }}"
        hasChanges=false
        for path in "${paths[@]}"; do
          # ensure path ends with /
          path="${path%/}/"

          # check if any file starts with the path
          if [[ ${{ steps.files.outputs.all }} == *"$path"* ]]; then
            hasChanges=true
            break
          fi
        done
        # set the output using the new way
        echo "hasChanges=$hasChanges" >> $GITHUB_OUTPUT

    - name: "Echo if there are changes"
      id: echoChanges
      shell: bash
      run: |
        echo "Has changes: ${{ steps.evaluateStep.outputs.hasChanges }}"