name: Evaluate Git Diff
description: "Evaluates the git diff and outputs the files that have been modified, added or deleted"

inputs:
  paths:
    description: "Paths to be verified, separated by comma"
    required: true
    default: "."

outputs:
  hasChanges:
    description: "Has changes"
    value: ${{ steps.evaluateStep.outputs.hasChanges }}
  pathsWithChanges:
    description: "Paths with changes (split by comma)"
    value: ${{ steps.evaluateStep.outputs.pathsWithChanges }}

runs:
  using: "composite"
  steps:
    # When the event is a workflow_run, we need to download the artifact
    # This artifact is being created by test-dotnet action, since this action usually triggers other workflows
    - name: "Load event commits from artifact (when event is workflow_run)"
      id: downloadEventCommitsArtifact
      if: ${{ github.event_name == 'workflow_run' }}
      uses: actions/download-artifact@v3
      with:
        name: ga-event-commits

    - name: Unzip event commits artifact
      id: unzipEventCommitsArtifact
      if: ${{ github.event_name == 'workflow_run' }}
      run: |
        unzip ga-event-commits.zip
        mv ga-event-commits.txt $GITHUB_OUTPUT

    - name: "Load event commits from ga-event-commits.txt"
      id: getEventCommitsFromEvent
      if: ${{ github.event_name != 'workflow_run' }}
      shell: bash
      run: |
        eventCommits=$(cat $GITHUB_EVENT_PATH/ga-event-commits.txt)
        echo "eventCommitsFromArtifact=$eventCommits" >> $GITHUB_OUTPUT

    - name: "Load event commits"
      id: getEventCommits
      shell: bash
      run: |
        eventCommits='${{ join(github.event.commits.*.id, ' ') }}'
        echo "eventCommits=$eventCommits" >> $GITHUB_OUTPUT

    - name: "Detect changes from event commits"
      id: files
      env:
        GITHUB_TOKEN: ${{ github.token }}
      shell: bash
      run: |
        # if getEventCommits is empty, should use eventCommitsFromArtifact
        commitShas="${{ steps.getEventCommits.outputs.eventCommits }}"

        if [[ -z $commitShas ]]; then
          commitShas="${{ steps.getEventCommitsFromEvent.outputs.eventCommitsFromArtifact }}"
        fi

        echo "[DEBUG] Event commits found: $commitShas"

        FILES=""
        for sha in $commitShas; do
          commits=$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "/repos/${{ github.repository }}/commits/${sha}")
          filenames=$(jq --join-output '.files[] | select(.status == "modified" or .status == "added") | "\(.filename) "' <<<"${commits}")
          for filename in $filenames; do
            # concat fileName to FILES split by comma if not already there
            if [[ $FILES != *"$filename"* ]]; then
              FILES="$filename,$FILES"
            fi
          done
        done
        FILES=${FILES::-1}
        echo "changedFiles=$FILES" >> $GITHUB_OUTPUT

    - name: "Evaluate Changes that are under the inputs.paths (split by comma)"
      id: evaluateStep
      shell: bash
      run: |
        inputPaths="${{ inputs.paths }}"

        echo "[DEBUG] Checking if any file starts with those paths: $inputPaths"
        echo "[DEBUG] Files loaded from event commits:"
        echo "${{ steps.files.outputs.changedFiles }}" | tr ',' '\n'

        # ensure inputPaths has at least one comma
        if [[ $inputPaths != *","* ]]; then
          inputPaths="$inputPaths,"
        fi

        # split the paths by comma
        IFS=',' read -ra paths <<< "${inputPaths}"

        # split files step output changedFiles by comma
        IFS=',' read -ra changedFiles <<< "${{ steps.files.outputs.changedFiles }}"

        hasChanges=false
        pathsWithChanges=""

        for path in "${paths[@]}"; do
          # ensure path does not start with ./
          if [[ $path == "./"* ]]; then
            path="${path#./}"
          fi

          # ensure path does not start with .
          if [[ $path == "."* ]]; then
            path="${path#.}"
          fi

          # ensure path ends with /
          path="${path%/}/"

          echo "[DEBUG] Checking path: $path"

          # if is root path, should always be true
          if [[ $path == "/" ]]; then
              echo "[DEBUG] Root path detected, all files are considered changed"
              pathsWithChanges="$path,$pathsWithChanges"
              hasChanges=true
          else
            # check if any file starts with the path
            for file in "${changedFiles[@]}"; do
              if [[ $file == "$path"* ]]; then
                echo "[DEBUG] Found changes in path $path"
                pathsWithChanges="$path,$pathsWithChanges"
                hasChanges=true
                break
              fi
            done
          fi
        done

        echo "[DEBUG] Paths with changes: $pathsWithChanges"
        pathsWithChanges=${pathsWithChanges:-1}

        # set the output with the result
        echo "hasChanges=$hasChanges" >> $GITHUB_OUTPUT
        echo "pathsWithChanges=$pathsWithChanges" >> $GITHUB_OUTPUT
