name: "Manual approval"
description: "Github action to require manual approval from specific users or org user groups. It will create an issue where approvers can comment to allow or deny the workflow run."

inputs:
  userReaderAppId:
    description: "Trakx User Reader Github App ID."
    required: true
  userReaderAppPrivateKey:
    description: "Trakx User Reader Github App Private Key."
    required: true
  approvers:
    description: "List of users or org user groups that can approve (separated by comma)."
    type: string
    required: true
  minimumApprovals:
    description: "Minimum number of approvals required."
    type: number
    required: false
    default: 1
  issueTitle:
    description: "Title of the issue to create."
    type: string
    required: false
    default: "Manual approval required"
  issuerCanApprove:
    description: "Blocks approval from the workflow run issuer."
    type: boolean
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: Generate token
      id: generate_token
      env:
        APP_ID: ${{ github.event.inputs.userReaderAppId }}
        PRIVATE_KEY: ${{ github.event.inputs.userReaderAppPrivateKey }}
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ env.APP_ID }}
        private_key: ${{ env.PRIVATE_KEY }}

    - name: Waiting for Approval
      uses: trstringer/manual-approval@v1.8.0
      env:
        GITHUB_READ_USERS_APP_TOKEN: ${{ steps.generate_token.outputs.token }}
        APPROVERS: ${{ github.event.inputs.approvers }}
        MINIMUM_APPROVALS: ${{ github.event.inputs.minimumApprovals }}
        ISSUE_TITLE: ${{ github.event.inputs.issueTitle }}
        EXCLUDE_WORKFLOW_INITIATOR_AS_APPROVER: ${{ github.event.inputs.issuerCanApprove }}
      with:
        secret: ${{ env.GITHUB_READ_USERS_APP_TOKEN }}
        approvers: "${{ env.APPROVERS }}"
        minimum-approvals: ${{ env.MINIMUM_APPROVALS }}
        issue-title: "${{ env.ISSUE_TITLE }}"
        exclude-workflow-initiator-as-approver: ${{ env.EXCLUDE_WORKFLOW_INITIATOR_AS_APPROVER }}
