name: "NEW - Publish nuget packages"
description: "Github action used to publish nuget packages to the private github nuget repository."

inputs:
  githubToken:
    description: "Access token provided by the calling action context, used to publish the packages and push the corresponding tag."
    required: true
  packageReadonlyPat:
    description: "Personal access token used to access the github private nuget source."
    required: true
  debuggable:
    description: "If true (default), publish a pre-release version. If false, publish a release version."
    required: false
    default: "true"
  semverIncrementLevel:
    description: "Level of the semver (major.minor.patch) to be increased to get the new package version."
    required: false
    default: "patch"
  actionsRepoRef:
    description: "Run actions from this ref. Default is master."
    required: false
    default: "master"
  dotnetVersion:
    description: "Version of dotnet to use."
    required: true

runs:
  using: "composite"
  steps:
    - name: Set compilation mode
      shell: bash
      id: comp-mode
      run: |
        if [ [${{ inputs.debuggable }} == f*] -o [${{ inputs.debuggable }} == F*] ]; then
          COMP_MODE=Release
        else
          COMP_MODE=Debug
        fi
        echo "compilationMode=$COMP_MODE" >> $GITHUB_OUTPUT
        echo "compilation mode set to $COMP_MODE"

    - name: Checkout
      uses: actions/checkout@v4

    - name: Checkout actions repo
      uses: actions/checkout@v4
      with:
        repository: trakx/github-actions
        path: ./github-actions-publish-nuget
        ref: ${{ inputs.actionsRepoRef }}

    - name: Load packable projects (and add them split by comma to an output)
      id: project-paths
      shell: bash
      run: |
        PROJECTS=""
        PATHS=""
        # find all projects that have the Packable.Projects.props file included
        for project in $(find ./src -name "*.csproj" -exec grep -rl "Packable.Projects.props" {} \;); do echo "packaging project $project" && \
          PROJECTS="$PROJECTS,$project";
        done
        PROJECTS=${PROJECTS:1}

        # get the path of the projects
        IFS=',' read -ra projectsList <<< "$PROJECTS"
        for projectCursor in "${projectsList[@]}"; do
          path=${projectCursor%/*}
          path="${path%/}/"
          PATHS="$PATHS,$path"
        done
        PATHS=${PATHS:1}

        echo "Projects available to publish: $PROJECTS"
        echo "Path of the projects available to publish: $PATHS"

        echo "projects=$PROJECTS" >> $GITHUB_OUTPUT
        echo "paths=$PATHS" >> $GITHUB_OUTPUT

    - name: Echo loaded project paths only (without the file, just the path)
      shell: bash
      run: |
        IFS=',' read -ra projects <<< "${{ steps.project-paths.outputs.all }}"
        for project in "${projects[@]}"; do
          echo "project path: ${project%/*}"
        done

    - name: Check if there are changes in the packable projects
      uses: ./github-actions-publish-nuget/git-diff
      id: git-diff
      with:
        paths: ${{ steps.project-paths.outputs.paths }}

    - name: Echo git diff output
      shell: bash
      run: |
        echo "hasChanges=${{ steps.git-diff.outputs.hasChanges }}"
        echo "changedFiles=${{ steps.git-diff.outputs.changedFiles }}"

    - name: Restore and cache private nuget packages
      if: ${{ steps.git-diff.outputs.hasChanges == 'true' }}
      uses: ./github-actions-publish-nuget/restore-dotnet
      with:
        dotnetVersion: ${{inputs.dotnetVersion}}
        packageReadonlyPat: ${{inputs.packageReadonlyPat}}

    - name: Bump version
      if: ${{ steps.git-diff.outputs.hasChanges == 'true' }}
      id: bumpVersion
      uses: ./github-actions-publish-nuget/get-tag
      with:
        semverIncrementLevel: ${{ inputs.semverIncrementLevel }}
        preRelease: ${{ inputs.debuggable }}

    - name: Build
      if: ${{ steps.git-diff.outputs.hasChanges == 'true' }}
      shell: bash
      run: |
        for f in $(find . -name "*.sln"); do echo "building solution $f" && \
          dotnet build $f \
            --configuration ${{steps.comp-mode.outputs.compilationMode}} \
            -p:Version=${{steps.bumpVersion.outputs.assemblyVersion}} \
            -p:SourceRevisionId=${{steps.bumpVersion.outputs.productVersion}} \
            --no-restore
        done

    - name: Package
      if: ${{ steps.git-diff.outputs.hasChanges == 'true' }}
      shell: bash
      run: |
        for project in $(find ./src -name "*.csproj" -exec grep -rl "Packable.Projects.props" {} \;); do echo "packaging project $project" && \
          dotnet pack $project --no-build --configuration ${{ steps.comp-mode.outputs.compilationMode }} \
            --output ./nuget/ -p:PackageVersion=${{steps.bumpVersion.outputs.fullVersion}} --include-symbols --include-source
        done

    - name: Publish
      if: ${{ steps.git-diff.outputs.hasChanges == 'true' }}
      shell: bash
      run: |
        ls ./nuget/*.nupkg
        for f in ./nuget/*.symbols.nupkg; \
          do echo "pushing $f file.." \
          && dotnet nuget push $f --api-key ${{inputs.githubToken}} --source "https://nuget.pkg.github.com/trakx/index.json";
        done

    - name: Push version tag
      if: ${{ steps.git-diff.outputs.hasChanges == 'true' }}
      id: pushTag
      uses: ./github-actions-publish-nuget/push-tag
      with:
        tag: v${{steps.bumpVersion.outputs.fullVersion}}
        githubToken: ${{inputs.githubToken}}
        preRelease: ${{ inputs.debuggable }}