name: "Deploy container image to Kubernetes"
description: "Deploy container image to Kubernetes. Requires deployment folder to be present in the repository."

inputs:
  environment:
    required: true
    type: string
  imageTag:
    required: true
    type: string
  serviceName:
    required: true
    type: string
  imageName:
    required: true
    type: string
  dockerRegistry:
    description: "Docker registry to push the image to."
    required: false
    type: string
    default: "docker.pkg.github.com"
  doCheckout:
    description: "Whether to checkout the repository or not."
    required: false
    type: boolean
    default: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      if: ${{inputs.doCheckout == true}}

    #Since github runners working in Docker-in-Docker mode we need this workaround
    - name: Install Kubernetes & Kustomize
      shell: bash
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
        curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
        sudo mv kustomize /usr/local/bin/kustomize

    - name: Deploy Image
      shell: bash
      run: |
        cd deployment/${{inputs.serviceName}}/overlays/${{inputs.environment}}/
        kustomize edit set image ${{inputs.serviceName}}=${{inputs.dockerRegistry}}/$GITHUB_REPOSITORY/${{inputs.imageName}}:${{inputs.imageTag}}
        kustomize build . | kubectl apply --validate=false -f -
