name: "Push tag"
description: "Github action trying to retrieve tag as artifact and push it."
inputs:
  tag:
    description: Use a custom tag and push it to the repo, a 'v' will be added automatically.
    required: true
  githubToken:
    description: GitHub token
    required: true

runs:
  using: "composite"
  steps:

    - name: Get commit shortened commit hash
      shell: bash
      id: existing_ref
      run: |
        set -o pipefail
        SOME_REF=$(git show-ref v0.2.20)
        echo '::set-output name=existing_ref::'$SOME_REF

    - name: show ref
      shell: bash
      id: show_ref
      run: |        
        echo ${{steps.existing_ref.outputs.existing_ref}}

    - name: Push tag
      if: ${{ steps.exists.outputs.tag_exists == 'false' }}
      uses: anothrNick/github-tag-action@1.39.0
      env:
        GITHUB_TOKEN: ${{inputs.githubToken}}
        DRY_RUN: 'false'
        CUSTOM_TAG: ${{inputs.tag}}
