name: "Print runner name"

on: 
  workflow_call:
    inputs: 
      runner_name:
        description: "Name of runner to print in the echo statement."
        type: string
        required: true
        default: "not-found"

jobs:
  print:
    runs-on: ${{inputs.runner_name}}

    steps:

    - name: Print runner name
      run: |
        echo "runner name is ${{inputs.runner_name}}"
