name: "Build, Push and Deploy a container image to Kubernetes"
# Requires `csproj` file contains `<EnableSdkContainerSupport>true</EnableSdkContainerSupport>` tag and a deployment folder to be present in the repository.

on:
  workflow_call:
    secrets:
      TRAKX_GITHUB_TOKEN:
        description: "Access token provided by the calling action context, used to publish the packages and push the corresponding tag."
        required: false
      TRAKX_BOT_READONLY_PAT:
        description: "Personal access token used to access the github private nuget source."
        required: true
    inputs:
      projectFolder:
        description: "Folder containing the project to build."
        required: true
        type: string
      serviceName:
        description: "Name of service being deployed."
        required: true
        type: string
      imageName:
        description: "Name of the docker image to build. If not provided, will be the same as 'serviceName'."
        required: false
        type: string
      runnerName:
        description: "Name of the runner to use. If not provided, will be generated based on the branch name."
        required: false
        type: string
        default: ''
      containerPublishType:
        description: "Type of container publish (api | worker). Default is api."
        required: false
        type: string
        default: 'api'
      dotnetVersion:
        description: "Version of dotnet to use. Default is v7.x."
        required: false
        type: string
        default: "7.x"
      dockerRegistry:
        description: "Docker registry to push the image to. Default is docker.pkg.github.com."
        required: false
        type: string
        default: "docker.pkg.github.com"

env:
  IMAGE_NAME: ${{ inputs.imageName || inputs.serviceName }}
  GITHUB_TOKEN: ${{ secrets.TRAKX_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

  prepare-and-validate:
    name: "Load and protect environment before jobs"
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.load-environment.outputs.environment }}
      runnerName: ${{ steps.load-environment.outputs.runnerName }}
      tagPrefix: ${{ steps.load-environment.outputs.tagPrefix }}
      actionsRepoReference: ${{ steps.get-ref-name.outputs.actionsRepoReference }}
    steps:
      - name: Checkout calling repo
        uses: actions/checkout@v3

      - name: Get ref_name
        id: get-ref-name
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            REF_NAME="${{ github.base_ref }}"
          else
            REF_NAME="${{ github.ref_name }}"
          fi
          echo "Detected actionsRepoReference: $REF_NAME"

          echo "Workflow ref ??: ${{ github.workflow_ref }}"
          echo "Action ref ??: ${{ github.action_ref }}"
          
          echo "actionsRepoReference=$REF_NAME" >> $GITHUB_OUTPUT
          exit 1

      - name: Checkout trakx/github-actions repo
        uses: actions/checkout@v3
        with:
          repository: trakx/github-actions
          path: ./github-actions-shared-build-deploy-container
          ref: ${{ steps.get-ref-name.outputs.actionsRepoReference }}

      - name: Load environment and runner
        id: load-environment
        uses: ./github-actions-shared-build-deploy-container/load-environment

      - name: Block workflow_dispatch for staging and production
        shell: bash
        run: |
          if [[ "${{ steps.load-environment.outputs.environment }}" == "production" || "${{ steps.load-environment.outputs.environment }}" == "staging" ]]; then
            if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
              echo "Event workflow_dispatch is not allowed for environment ${{ steps.load-environment.outputs.environment }}."
              exit 1
            fi
          fi

  build-push-container-image:
    name: "Build and push container image"
    needs: [ prepare-and-validate ]
    runs-on: ${{ needs.prepare-and-validate.outputs.runnerName }}
    steps:
      - name: Checkout calling repo
        uses: actions/checkout@v3

      - name: Checkout trakx/github-actions repo
        uses: actions/checkout@v3
        with:
          repository: trakx/github-actions
          path: ./github-actions-shared-build-deploy-container
          ref: ${{ needs.prepare-and-validate.outputs.actionsRepoReference }}

      - name: Get last commit of calling repo
        id: last-commit-sha
        uses: ./github-actions-shared-build-deploy-container/get-last-commit

      - name: Build and push container image
        id: build-push-container-image-step
        uses: ./github-actions-shared-build-deploy-container/build-push-container-image
        with:
          githubToken: ${{ env.GITHUB_TOKEN }}
          packageReadonlyPat: ${{ secrets.TRAKX_BOT_READONLY_PAT }}
          projectFolder: ${{ inputs.projectFolder }}
          imageName: ${{ env.IMAGE_NAME }}
          imageTagPrefix: ${{ needs.prepare-and-validate.outputs.tagPrefix }}
          containerPublishType: ${{ inputs.containerPublishType }}
          dotnetVersion: ${{ inputs.dotnetVersion }}
          dockerRegistry: ${{ inputs.dockerRegistry }}
          imageTagSuffix: ${{ steps.last-commit-sha.outputs.lastCommitSha }}
          actionsRepoRef: ${{ needs.prepare-and-validate.outputs.actionsRepoReference }}
          doCheckout: false
    outputs:
      tag: ${{ steps.build-push-container-image-step.outputs.tag }}

  deploy-kubernetes:
    name: "Deploy image to Kubernetes"
    needs: [ prepare-and-validate, build-push-container-image ]
    runs-on: ${{ needs.prepare-and-validate.outputs.runnerName }}
    if: |
      always() &&
        (needs.build-push-container-image.result == 'success' || (needs.build-push-container-image.result == 'skipped'
            && github.event_name == 'workflow_run'
            && github.event.workflow_run.conclusion == 'success' ))
    steps:
      - name: Checkout calling repo
        uses: actions/checkout@v3

      - name: Checkout trakx/github-actions repo
        uses: actions/checkout@v3
        with:
          repository: trakx/github-actions
          path: ./github-actions-shared-build-deploy-container
          ref: ${{ needs.prepare-and-validate.outputs.actionsRepoReference }}

      - name: Deploy container image to Kubernetes
        id: deploy-container-k8s
        uses: ./github-actions-shared-build-deploy-container/deploy
        with:
          githubToken: ${{ env.GITHUB_TOKEN }}
          tag: ${{ needs.build-push-container-image.outputs.tag }}
          service: ${{ inputs.serviceName }}
          artifact-name: ${{ env.IMAGE_NAME }}
          serviceRegistry: ${{ inputs.dockerRegistry }}
          type: "kubernetes"
          actionsRepoRef: ${{ needs.prepare-and-validate.outputs.actionsRepoReference }}
