name: Test workflow

on:
  workflow_dispatch:
    inputs:
      runner:
        description: Runner name
        required: true
        default: 'dev-trakx-runner'

env:
  RUNNER: ${{github.event.inputs.runner}}

jobs:
  do_dev:
    runs-on: dev-trakx-runner
    if: github.event.inputs.runner == 'dev-trakx-runner'

    steps:

    - name: Print runner name
      run: |
        echo "runner name is ${{github.event.inputs.runner}}"

  do_stage:
    runs-on: stage-trakx-runner
    if: github.event.inputs.runner == 'stage-trakx-runner'

    steps:

    - name: Print runner name
      run: |
        echo "runner name is ${{github.event.inputs.runner}}"

